
name: Setup
description: Setup Python and Poetry

inputs:
  python-version:
    description: Python version to use
    required: true
    default: "3.10"
  poetry-version:
    description: Poetry version to use
    required: true
    default: "1.5.1"
  poetry-url:
    description: Poetry installation URL
    required: true
    default: https://install.python-poetry.org/

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache Poetry cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ inputs.poetry-version }}

    - name: Cache Packages
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}-${{ hashFiles('.github/actions/*.yml') }}

    - name: Install Poetry ${{ inputs.poetry-version }}
      shell: bash
      run: |
        curl -sSL ${{ inputs.poetry-url }} | python - --version ${{ inputs.poetry-version }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      shell: bash
      run: poetry install
