name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup using the custom action in .github/actions/setup.yml
        uses: ./.github/actions/setup

      - name: Run black
        run: |
          poetry run black --check --diff custom_components/hass_day_state

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup using the custom action in .github/actions/setup.yml
        uses: ./.github/actions/setup

      - name: Run isort
        run: |
          poetry run isort --check-only --diff --profile black custom_components/hass_day_state

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup using the custom action in .github/actions/setup.yml
        uses: ./.github/actions/setup

      - name: Run mypy
        run: |
          poetry run mypy custom_components/hass_day_state --ignore-missing-imports

  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup using the custom action in .github/actions/setup.yml
        uses: ./.github/actions/setup

      - name: Run bandit
        run: |
          poetry run bandit -r custom_components/hass_day_state

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup using the custom action in .github/actions/setup.yml
        uses: ./.github/actions/setup

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup using the custom action in .github/actions/setup.yml
        uses: ./.github/actions/setup

      - name: Run hacs
        uses: hacs/action@main
        with:
          category: integration
